// Copyright 2012 The go-sdl2 Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package sdl

/*
#include "SDL.h"
*/
import "C"

// The SDL virtual key representation.
//
// Values of this type are used to represent keyboard keys using the current
// layout of the keyboard.  These values include Unicode values representing
// the unmodified character that would be generated by pressing the key, or
// an K_* constant for those keys that do not generate characters.
type Keycode int32

const (
	K_UNKNOWN Keycode = C.SDLK_UNKNOWN

	K_RETURN       Keycode = C.SDLK_RETURN
	K_ESCAPE       Keycode = C.SDLK_ESCAPE
	K_BACKSPACE    Keycode = C.SDLK_BACKSPACE
	K_TAB          Keycode = C.SDLK_TAB
	K_SPACE        Keycode = C.SDLK_SPACE
	K_EXCLAIM      Keycode = C.SDLK_EXCLAIM
	K_QUOTEDBL     Keycode = C.SDLK_QUOTEDBL
	K_HASH         Keycode = C.SDLK_HASH
	K_PERCENT      Keycode = C.SDLK_PERCENT
	K_DOLLAR       Keycode = C.SDLK_DOLLAR
	K_AMPERSAND    Keycode = C.SDLK_AMPERSAND
	K_QUOTE        Keycode = C.SDLK_QUOTE
	K_LEFTPAREN    Keycode = C.SDLK_LEFTPAREN
	K_RIGHTPAREN   Keycode = C.SDLK_RIGHTPAREN
	K_ASTERISK     Keycode = C.SDLK_ASTERISK
	K_PLUS         Keycode = C.SDLK_PLUS
	K_COMMA        Keycode = C.SDLK_COMMA
	K_MINUS        Keycode = C.SDLK_MINUS
	K_PERIOD       Keycode = C.SDLK_PERIOD
	K_SLASH        Keycode = C.SDLK_SLASH
	K_0            Keycode = C.SDLK_0
	K_1            Keycode = C.SDLK_1
	K_2            Keycode = C.SDLK_2
	K_3            Keycode = C.SDLK_3
	K_4            Keycode = C.SDLK_4
	K_5            Keycode = C.SDLK_5
	K_6            Keycode = C.SDLK_6
	K_7            Keycode = C.SDLK_7
	K_8            Keycode = C.SDLK_8
	K_9            Keycode = C.SDLK_9
	K_COLON        Keycode = C.SDLK_COLON
	K_SEMICOLON    Keycode = C.SDLK_SEMICOLON
	K_LESS         Keycode = C.SDLK_LESS
	K_EQUALS       Keycode = C.SDLK_EQUALS
	K_GREATER      Keycode = C.SDLK_GREATER
	K_QUESTION     Keycode = C.SDLK_QUESTION
	K_AT           Keycode = C.SDLK_AT
	K_LEFTBRACKET  Keycode = C.SDLK_LEFTBRACKET
	K_BACKSLASH    Keycode = C.SDLK_BACKSLASH
	K_RIGHTBRACKET Keycode = C.SDLK_RIGHTBRACKET
	K_CARET        Keycode = C.SDLK_CARET
	K_UNDERSCORE   Keycode = C.SDLK_UNDERSCORE
	K_BACKQUOTE    Keycode = C.SDLK_BACKQUOTE
	K_a            Keycode = C.SDLK_a
	K_b            Keycode = C.SDLK_b
	K_c            Keycode = C.SDLK_c
	K_d            Keycode = C.SDLK_d
	K_e            Keycode = C.SDLK_e
	K_f            Keycode = C.SDLK_f
	K_g            Keycode = C.SDLK_g
	K_h            Keycode = C.SDLK_h
	K_i            Keycode = C.SDLK_i
	K_j            Keycode = C.SDLK_j
	K_k            Keycode = C.SDLK_k
	K_l            Keycode = C.SDLK_l
	K_m            Keycode = C.SDLK_m
	K_n            Keycode = C.SDLK_n
	K_o            Keycode = C.SDLK_o
	K_p            Keycode = C.SDLK_p
	K_q            Keycode = C.SDLK_q
	K_r            Keycode = C.SDLK_r
	K_s            Keycode = C.SDLK_s
	K_t            Keycode = C.SDLK_t
	K_u            Keycode = C.SDLK_u
	K_v            Keycode = C.SDLK_v
	K_w            Keycode = C.SDLK_w
	K_x            Keycode = C.SDLK_x
	K_y            Keycode = C.SDLK_y
	K_z            Keycode = C.SDLK_z

	K_CAPSLOCK Keycode = C.SDLK_CAPSLOCK

	K_F1  Keycode = C.SDLK_F1
	K_F2  Keycode = C.SDLK_F2
	K_F3  Keycode = C.SDLK_F3
	K_F4  Keycode = C.SDLK_F4
	K_F5  Keycode = C.SDLK_F5
	K_F6  Keycode = C.SDLK_F6
	K_F7  Keycode = C.SDLK_F7
	K_F8  Keycode = C.SDLK_F8
	K_F9  Keycode = C.SDLK_F9
	K_F10 Keycode = C.SDLK_F10
	K_F11 Keycode = C.SDLK_F11
	K_F12 Keycode = C.SDLK_F12

	K_PRINTSCREEN Keycode = C.SDLK_PRINTSCREEN
	K_SCROLLLOCK  Keycode = C.SDLK_SCROLLLOCK
	K_PAUSE       Keycode = C.SDLK_PAUSE
	K_INSERT      Keycode = C.SDLK_INSERT
	K_HOME        Keycode = C.SDLK_HOME
	K_PAGEUP      Keycode = C.SDLK_PAGEUP
	K_DELETE      Keycode = C.SDLK_DELETE
	K_END         Keycode = C.SDLK_END
	K_PAGEDOWN    Keycode = C.SDLK_PAGEDOWN
	K_RIGHT       Keycode = C.SDLK_RIGHT
	K_LEFT        Keycode = C.SDLK_LEFT
	K_DOWN        Keycode = C.SDLK_DOWN
	K_UP          Keycode = C.SDLK_UP

	K_NUMLOCKCLEAR Keycode = C.SDLK_NUMLOCKCLEAR
	K_KP_DIVIDE    Keycode = C.SDLK_KP_DIVIDE
	K_KP_MULTIPLY  Keycode = C.SDLK_KP_MULTIPLY
	K_KP_MINUS     Keycode = C.SDLK_KP_MINUS
	K_KP_PLUS      Keycode = C.SDLK_KP_PLUS
	K_KP_ENTER     Keycode = C.SDLK_KP_ENTER
	K_KP_1         Keycode = C.SDLK_KP_1
	K_KP_2         Keycode = C.SDLK_KP_2
	K_KP_3         Keycode = C.SDLK_KP_3
	K_KP_4         Keycode = C.SDLK_KP_4
	K_KP_5         Keycode = C.SDLK_KP_5
	K_KP_6         Keycode = C.SDLK_KP_6
	K_KP_7         Keycode = C.SDLK_KP_7
	K_KP_8         Keycode = C.SDLK_KP_8
	K_KP_9         Keycode = C.SDLK_KP_9
	K_KP_0         Keycode = C.SDLK_KP_0
	K_KP_PERIOD    Keycode = C.SDLK_KP_PERIOD

	K_APPLICATION    Keycode = C.SDLK_APPLICATION
	K_POWER          Keycode = C.SDLK_POWER
	K_KP_EQUALS      Keycode = C.SDLK_KP_EQUALS
	K_F13            Keycode = C.SDLK_F13
	K_F14            Keycode = C.SDLK_F14
	K_F15            Keycode = C.SDLK_F15
	K_F16            Keycode = C.SDLK_F16
	K_F17            Keycode = C.SDLK_F17
	K_F18            Keycode = C.SDLK_F18
	K_F19            Keycode = C.SDLK_F19
	K_F20            Keycode = C.SDLK_F20
	K_F21            Keycode = C.SDLK_F21
	K_F22            Keycode = C.SDLK_F22
	K_F23            Keycode = C.SDLK_F23
	K_F24            Keycode = C.SDLK_F24
	K_EXECUTE        Keycode = C.SDLK_EXECUTE
	K_HELP           Keycode = C.SDLK_HELP
	K_MENU           Keycode = C.SDLK_MENU
	K_SELECT         Keycode = C.SDLK_SELECT
	K_STOP           Keycode = C.SDLK_STOP
	K_AGAIN          Keycode = C.SDLK_AGAIN
	K_UNDO           Keycode = C.SDLK_UNDO
	K_CUT            Keycode = C.SDLK_CUT
	K_COPY           Keycode = C.SDLK_COPY
	K_PASTE          Keycode = C.SDLK_PASTE
	K_FIND           Keycode = C.SDLK_FIND
	K_MUTE           Keycode = C.SDLK_MUTE
	K_VOLUMEUP       Keycode = C.SDLK_VOLUMEUP
	K_VOLUMEDOWN     Keycode = C.SDLK_VOLUMEDOWN
	K_KP_COMMA       Keycode = C.SDLK_KP_COMMA
	K_KP_EQUALSAS400 Keycode = C.SDLK_KP_EQUALSAS400

	K_ALTERASE   Keycode = C.SDLK_ALTERASE
	K_SYSREQ     Keycode = C.SDLK_SYSREQ
	K_CANCEL     Keycode = C.SDLK_CANCEL
	K_CLEAR      Keycode = C.SDLK_CLEAR
	K_PRIOR      Keycode = C.SDLK_PRIOR
	K_RETURN2    Keycode = C.SDLK_RETURN2
	K_SEPARATOR  Keycode = C.SDLK_SEPARATOR
	K_OUT        Keycode = C.SDLK_OUT
	K_OPER       Keycode = C.SDLK_OPER
	K_CLEARAGAIN Keycode = C.SDLK_CLEARAGAIN
	K_CRSEL      Keycode = C.SDLK_CRSEL
	K_EXSEL      Keycode = C.SDLK_EXSEL

	K_KP_00              Keycode = C.SDLK_KP_00
	K_KP_000             Keycode = C.SDLK_KP_000
	K_THOUSANDSSEPARATOR Keycode = C.SDLK_THOUSANDSSEPARATOR
	K_DECIMALSEPARATOR   Keycode = C.SDLK_DECIMALSEPARATOR
	K_CURRENCYUNIT       Keycode = C.SDLK_CURRENCYUNIT
	K_CURRENCYSUBUNIT    Keycode = C.SDLK_CURRENCYSUBUNIT
	K_KP_LEFTPAREN       Keycode = C.SDLK_KP_LEFTPAREN
	K_KP_RIGHTPAREN      Keycode = C.SDLK_KP_RIGHTPAREN
	K_KP_LEFTBRACE       Keycode = C.SDLK_KP_LEFTBRACE
	K_KP_RIGHTBRACE      Keycode = C.SDLK_KP_RIGHTBRACE
	K_KP_TAB             Keycode = C.SDLK_KP_TAB
	K_KP_BACKSPACE       Keycode = C.SDLK_KP_BACKSPACE
	K_KP_A               Keycode = C.SDLK_KP_A
	K_KP_B               Keycode = C.SDLK_KP_B
	K_KP_C               Keycode = C.SDLK_KP_C
	K_KP_D               Keycode = C.SDLK_KP_D
	K_KP_E               Keycode = C.SDLK_KP_E
	K_KP_F               Keycode = C.SDLK_KP_F
	K_KP_XOR             Keycode = C.SDLK_KP_XOR
	K_KP_POWER           Keycode = C.SDLK_KP_POWER
	K_KP_PERCENT         Keycode = C.SDLK_KP_PERCENT
	K_KP_LESS            Keycode = C.SDLK_KP_LESS
	K_KP_GREATER         Keycode = C.SDLK_KP_GREATER
	K_KP_AMPERSAND       Keycode = C.SDLK_KP_AMPERSAND
	K_KP_DBLAMPERSAND    Keycode = C.SDLK_KP_DBLAMPERSAND
	K_KP_VERTICALBAR     Keycode = C.SDLK_KP_VERTICALBAR
	K_KP_DBLVERTICALBAR  Keycode = C.SDLK_KP_DBLVERTICALBAR
	K_KP_COLON           Keycode = C.SDLK_KP_COLON
	K_KP_HASH            Keycode = C.SDLK_KP_HASH
	K_KP_SPACE           Keycode = C.SDLK_KP_SPACE
	K_KP_AT              Keycode = C.SDLK_KP_AT
	K_KP_EXCLAM          Keycode = C.SDLK_KP_EXCLAM
	K_KP_MEMSTORE        Keycode = C.SDLK_KP_MEMSTORE
	K_KP_MEMRECALL       Keycode = C.SDLK_KP_MEMRECALL
	K_KP_MEMCLEAR        Keycode = C.SDLK_KP_MEMCLEAR
	K_KP_MEMADD          Keycode = C.SDLK_KP_MEMADD
	K_KP_MEMSUBTRACT     Keycode = C.SDLK_KP_MEMSUBTRACT
	K_KP_MEMMULTIPLY     Keycode = C.SDLK_KP_MEMMULTIPLY
	K_KP_MEMDIVIDE       Keycode = C.SDLK_KP_MEMDIVIDE
	K_KP_PLUSMINUS       Keycode = C.SDLK_KP_PLUSMINUS
	K_KP_CLEAR           Keycode = C.SDLK_KP_CLEAR
	K_KP_CLEARENTRY      Keycode = C.SDLK_KP_CLEARENTRY
	K_KP_BINARY          Keycode = C.SDLK_KP_BINARY
	K_KP_OCTAL           Keycode = C.SDLK_KP_OCTAL
	K_KP_DECIMAL         Keycode = C.SDLK_KP_DECIMAL
	K_KP_HEXADECIMAL     Keycode = C.SDLK_KP_HEXADECIMAL

	K_LCTRL  Keycode = C.SDLK_LCTRL
	K_LSHIFT Keycode = C.SDLK_LSHIFT
	K_LALT   Keycode = C.SDLK_LALT
	K_LGUI   Keycode = C.SDLK_LGUI
	K_RCTRL  Keycode = C.SDLK_RCTRL
	K_RSHIFT Keycode = C.SDLK_RSHIFT
	K_RALT   Keycode = C.SDLK_RALT
	K_RGUI   Keycode = C.SDLK_RGUI

	K_MODE Keycode = C.SDLK_MODE

	K_AUDIONEXT    Keycode = C.SDLK_AUDIONEXT
	K_AUDIOPREV    Keycode = C.SDLK_AUDIOPREV
	K_AUDIOSTOP    Keycode = C.SDLK_AUDIOSTOP
	K_AUDIOPLAY    Keycode = C.SDLK_AUDIOPLAY
	K_AUDIOMUTE    Keycode = C.SDLK_AUDIOMUTE
	K_MEDIASELECT  Keycode = C.SDLK_MEDIASELECT
	K_WWW          Keycode = C.SDLK_WWW
	K_MAIL         Keycode = C.SDLK_MAIL
	K_CALCULATOR   Keycode = C.SDLK_CALCULATOR
	K_COMPUTER     Keycode = C.SDLK_COMPUTER
	K_AC_SEARCH    Keycode = C.SDLK_AC_SEARCH
	K_AC_HOME      Keycode = C.SDLK_AC_HOME
	K_AC_BACK      Keycode = C.SDLK_AC_BACK
	K_AC_FORWARD   Keycode = C.SDLK_AC_FORWARD
	K_AC_STOP      Keycode = C.SDLK_AC_STOP
	K_AC_REFRESH   Keycode = C.SDLK_AC_REFRESH
	K_AC_BOOKMARKS Keycode = C.SDLK_AC_BOOKMARKS

	K_BRIGHTNESSDOWN Keycode = C.SDLK_BRIGHTNESSDOWN
	K_BRIGHTNESSUP   Keycode = C.SDLK_BRIGHTNESSUP
	K_DISPLAYSWITCH  Keycode = C.SDLK_DISPLAYSWITCH
	K_KBDILLUMTOGGLE Keycode = C.SDLK_KBDILLUMTOGGLE
	K_KBDILLUMDOWN   Keycode = C.SDLK_KBDILLUMDOWN
	K_KBDILLUMUP     Keycode = C.SDLK_KBDILLUMUP
	K_EJECT          Keycode = C.SDLK_EJECT
	K_SLEEP          Keycode = C.SDLK_SLEEP
)

type Keymod uint16

const (
	KMOD_NONE     Keymod = C.KMOD_NONE
	KMOD_LSHIFT   Keymod = C.KMOD_LSHIFT
	KMOD_RSHIFT   Keymod = C.KMOD_RSHIFT
	KMOD_LCTRL    Keymod = C.KMOD_LCTRL
	KMOD_RCTRL    Keymod = C.KMOD_RCTRL
	KMOD_LALT     Keymod = C.KMOD_LALT
	KMOD_RALT     Keymod = C.KMOD_RALT
	KMOD_LGUI     Keymod = C.KMOD_LGUI
	KMOD_RGUI     Keymod = C.KMOD_RGUI
	KMOD_NUM      Keymod = C.KMOD_NUM
	KMOD_CAPS     Keymod = C.KMOD_CAPS
	KMOD_MODE     Keymod = C.KMOD_MODE
	KMOD_RESERVED Keymod = C.KMOD_RESERVED
	KMOD_CTRL     Keymod = C.KMOD_CTRL
	KMOD_SHIFT    Keymod = C.KMOD_SHIFT
	KMOD_ALT      Keymod = C.KMOD_ALT
	KMOD_GUI      Keymod = C.KMOD_GUI
)
